version: "3.8"

services:
  rabbit:
    image: rabbitmq:3.12.4-management
    restart: always
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_ADMIN_PORT:-15672}:15672"
    volumes:
      - "rabbit:/var/lib/rabbitmq"

  db:
    image: ankane/pgvector:v0.5.0
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  redis:
    image: redis:7.2
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - "redis:/var/lib/redis"

volumes:
  rabbit:
  pgdata:
  redis:
